### ISSUE TITLE
Bug - Feature - List of employees

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/lms-core#1]
Scenario
As a user/admin, I need to get the list of employees
Bug:
executeUpdate will not retrieve the ResultSet.

Screenshots:
![image](https://user-images.githubusercontent.com/22638364/126070205-cda25175-3a34-403f-a71d-7c4c5a8f43de.png)

**Comment by lkarthi** [comment]
I have fixed this issue.

**Comment by nareshkumar-h** [comment]
![image](https://user-images.githubusercontent.com/2763774/126280489-bbb7cb0c-0552-4781-95f1-a5860e6f386f.png)

**Comment by Rekashanmugam** [comment]
Sir, This issue is fixed kindly check.

**Comment by selvianu** [comment]
fixed. working.
