### ISSUE TITLE
Bug - Feature - Add New User/Login user 

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/lms-core#2]
Scenario: 
When added as a new user, the same should be as the Login. 
Bug:
A new user table and different login table. record from user table is not updated in login table.
new user table is no longer used. to list the employee details, login table is used

![image](https://user-images.githubusercontent.com/22638364/126070785-b884cc67-bdfc-459e-b2b3-005bf16d2565.png)

**Comment by arunr1812** [comment]
I have fixed this issue already by using inserting new user into login table

**Comment by nareshkumar-h** [comment]
Add New user records/details should be used as user login.

**Comment by arunr1812** [comment]
issue fixed now by arun
