### ISSUE TITLE
Bug - ConnectionUtil 

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/lms-core#3]
Scenario: 
As a developer, my code should have reusability
Bug: 
ConnectionUtil class is written in all classes

Screenshot: 
![image](https://user-images.githubusercontent.com/22638364/126072851-42b2eb0d-579a-4ce7-ab87-e968bc192179.png)

![image](https://user-images.githubusercontent.com/22638364/126072885-f1f8393f-7605-4d24-93ef-0c97d50bef68.png)

![image](https://user-images.githubusercontent.com/22638364/126072899-4624029d-fb76-4ace-ae48-9a9aabe41cfc.png)

**Comment by lkarthi** [comment]
I have Created ConnectionUtil and then fixed

**Comment by selvianu** [comment]
I meant, You shouldn't repeat the same connection util

 (String driverClassName = System.getenv("DB_DRIVER_NAME");
		String url = System.getenv("DB_URL");
		String username = System.getenv("DB_USERNAME");
		String password = System.getenv("DB_PASSWORD");)
		
The above snippet is repeated in many classes.
The above snippet should in a separate method and it should be invoked where ever needed.


![image](https://user-images.githubusercontent.com/22638364/126275537-d4d196d8-9b78-4800-94f0-1477e07884cf.png)


![image](https://user-images.githubusercontent.com/22638364/126275585-dc83a5eb-703d-41aa-9911-44bac812e507.png)


![image](https://user-images.githubusercontent.com/22638364/126275629-5ffba8c2-db72-4d0d-87a2-d757999beb4e.png)


![image](https://user-images.githubusercontent.com/22638364/126275777-561f93d6-ce31-4557-b2f0-f76860675849.png)

**Comment by Rekashanmugam** [comment]
This issue is fixed kindly check it out.

**Comment by selvianu** [comment]
fixed. working as expected
